(cl:in-package dobot_v4_bringup-srv)
(cl:export '(MODE-VAL
          MODE
          A-VAL
          A
          B-VAL
          B
          C-VAL
          C
          D-VAL
          D
          E-VAL
          E
          F-VAL
          F
          A2-VAL
          A2
          B2-VAL
          B2
          C2-VAL
          C2
          D2-VAL
          D2
          E2-VAL
          E2
          F2-VAL
          F2
          PARAMVALUE-VAL
          PARAMVALUE
          RES-VAL
          RES
))