// Generated by gencpp from file rosdemo_v4/GetErrorID.msg
// DO NOT EDIT!


#ifndef ROSDEMO_V4_MESSAGE_GETERRORID_H
#define ROSDEMO_V4_MESSAGE_GETERRORID_H

#include <ros/service_traits.h>


#include <rosdemo_v4/GetErrorIDRequest.h>
#include <rosdemo_v4/GetErrorIDResponse.h>


namespace rosdemo_v4
{

struct GetErrorID
{

typedef GetErrorIDRequest Request;
typedef GetErrorIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetErrorID
} // namespace rosdemo_v4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosdemo_v4::GetErrorID > {
  static const char* value()
  {
    return "15273c96ecb6b320e7c1e60e17abe5ab";
  }

  static const char* value(const ::rosdemo_v4::GetErrorID&) { return value(); }
};

template<>
struct DataType< ::rosdemo_v4::GetErrorID > {
  static const char* value()
  {
    return "rosdemo_v4/GetErrorID";
  }

  static const char* value(const ::rosdemo_v4::GetErrorID&) { return value(); }
};


// service_traits::MD5Sum< ::rosdemo_v4::GetErrorIDRequest> should match
// service_traits::MD5Sum< ::rosdemo_v4::GetErrorID >
template<>
struct MD5Sum< ::rosdemo_v4::GetErrorIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosdemo_v4::GetErrorID >::value();
  }
  static const char* value(const ::rosdemo_v4::GetErrorIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdemo_v4::GetErrorIDRequest> should match
// service_traits::DataType< ::rosdemo_v4::GetErrorID >
template<>
struct DataType< ::rosdemo_v4::GetErrorIDRequest>
{
  static const char* value()
  {
    return DataType< ::rosdemo_v4::GetErrorID >::value();
  }
  static const char* value(const ::rosdemo_v4::GetErrorIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosdemo_v4::GetErrorIDResponse> should match
// service_traits::MD5Sum< ::rosdemo_v4::GetErrorID >
template<>
struct MD5Sum< ::rosdemo_v4::GetErrorIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosdemo_v4::GetErrorID >::value();
  }
  static const char* value(const ::rosdemo_v4::GetErrorIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdemo_v4::GetErrorIDResponse> should match
// service_traits::DataType< ::rosdemo_v4::GetErrorID >
template<>
struct DataType< ::rosdemo_v4::GetErrorIDResponse>
{
  static const char* value()
  {
    return DataType< ::rosdemo_v4::GetErrorID >::value();
  }
  static const char* value(const ::rosdemo_v4::GetErrorIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSDEMO_V4_MESSAGE_GETERRORID_H
