// Generated by gencpp from file rosdemo_v4/MovJRequest.msg
// DO NOT EDIT!


#ifndef ROSDEMO_V4_MESSAGE_MOVJREQUEST_H
#define ROSDEMO_V4_MESSAGE_MOVJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosdemo_v4
{
template <class ContainerAllocator>
struct MovJRequest_
{
  typedef MovJRequest_<ContainerAllocator> Type;

  MovJRequest_()
    : mode(false)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)
    , paramValue()  {
    }
  MovJRequest_(const ContainerAllocator& _alloc)
    : mode(false)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;

   typedef double _e_type;
  _e_type e;

   typedef double _f_type;
  _f_type f;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::rosdemo_v4::MovJRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosdemo_v4::MovJRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MovJRequest_

typedef ::rosdemo_v4::MovJRequest_<std::allocator<void> > MovJRequest;

typedef boost::shared_ptr< ::rosdemo_v4::MovJRequest > MovJRequestPtr;
typedef boost::shared_ptr< ::rosdemo_v4::MovJRequest const> MovJRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosdemo_v4::MovJRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosdemo_v4::MovJRequest_<ContainerAllocator1> & lhs, const ::rosdemo_v4::MovJRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e &&
    lhs.f == rhs.f &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosdemo_v4::MovJRequest_<ContainerAllocator1> & lhs, const ::rosdemo_v4::MovJRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosdemo_v4

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosdemo_v4::MovJRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosdemo_v4::MovJRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdemo_v4::MovJRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87e876bc8a2d6739c81f81ad324bafb5";
  }

  static const char* value(const ::rosdemo_v4::MovJRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87e876bc8a2d6739ULL;
  static const uint64_t static_value2 = 0xc81f81ad324bafb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosdemo_v4/MovJRequest";
  }

  static const char* value(const ::rosdemo_v4::MovJRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool mode\n"
"float64 a\n"
"float64 b\n"
"float64 c\n"
"float64 d\n"
"float64 e\n"
"float64 f\n"
"string[] paramValue\n"
;
  }

  static const char* value(const ::rosdemo_v4::MovJRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
      stream.next(m.f);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovJRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosdemo_v4::MovJRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosdemo_v4::MovJRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "e: ";
    Printer<double>::stream(s, indent + "  ", v.e);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "f: ";
    Printer<double>::stream(s, indent + "  ", v.f);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "paramValue: ";
    if (v.paramValue.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.paramValue[i]);
    }
    if (v.paramValue.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSDEMO_V4_MESSAGE_MOVJREQUEST_H
