// Generated by gencpp from file active_grasp/ResetResponse.msg
// DO NOT EDIT!


#ifndef ACTIVE_GRASP_MESSAGE_RESETRESPONSE_H
#define ACTIVE_GRASP_MESSAGE_RESETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <active_grasp/AABBox.h>

namespace active_grasp
{
template <class ContainerAllocator>
struct ResetResponse_
{
  typedef ResetResponse_<ContainerAllocator> Type;

  ResetResponse_()
    : bbox()  {
    }
  ResetResponse_(const ContainerAllocator& _alloc)
    : bbox(_alloc)  {
  (void)_alloc;
    }



   typedef  ::active_grasp::AABBox_<ContainerAllocator>  _bbox_type;
  _bbox_type bbox;





  typedef boost::shared_ptr< ::active_grasp::ResetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::active_grasp::ResetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetResponse_

typedef ::active_grasp::ResetResponse_<std::allocator<void> > ResetResponse;

typedef boost::shared_ptr< ::active_grasp::ResetResponse > ResetResponsePtr;
typedef boost::shared_ptr< ::active_grasp::ResetResponse const> ResetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::active_grasp::ResetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::active_grasp::ResetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::active_grasp::ResetResponse_<ContainerAllocator1> & lhs, const ::active_grasp::ResetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.bbox == rhs.bbox;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::active_grasp::ResetResponse_<ContainerAllocator1> & lhs, const ::active_grasp::ResetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace active_grasp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::active_grasp::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::active_grasp::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::active_grasp::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::active_grasp::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::active_grasp::ResetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::active_grasp::ResetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::active_grasp::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dd9de15958dc8059c48f7ba8054e4b8";
  }

  static const char* value(const ::active_grasp::ResetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dd9de15958dc805ULL;
  static const uint64_t static_value2 = 0x9c48f7ba8054e4b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::active_grasp::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "active_grasp/ResetResponse";
  }

  static const char* value(const ::active_grasp::ResetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::active_grasp::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "active_grasp/AABBox bbox\n"
"\n"
"\n"
"================================================================================\n"
"MSG: active_grasp/AABBox\n"
"  geometry_msgs/Point min\n"
"  geometry_msgs/Point max\n"
"  \n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::active_grasp::ResetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::active_grasp::ResetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bbox);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::active_grasp::ResetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::active_grasp::ResetResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "bbox: ";
    Printer< ::active_grasp::AABBox_<ContainerAllocator> >::stream(s, indent + "  ", v.bbox);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIVE_GRASP_MESSAGE_RESETRESPONSE_H
