// Generated by gencpp from file active_grasp/SeedRequest.msg
// DO NOT EDIT!


#ifndef ACTIVE_GRASP_MESSAGE_SEEDREQUEST_H
#define ACTIVE_GRASP_MESSAGE_SEEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace active_grasp
{
template <class ContainerAllocator>
struct SeedRequest_
{
  typedef SeedRequest_<ContainerAllocator> Type;

  SeedRequest_()
    : seed(0)  {
    }
  SeedRequest_(const ContainerAllocator& _alloc)
    : seed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _seed_type;
  _seed_type seed;





  typedef boost::shared_ptr< ::active_grasp::SeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::active_grasp::SeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SeedRequest_

typedef ::active_grasp::SeedRequest_<std::allocator<void> > SeedRequest;

typedef boost::shared_ptr< ::active_grasp::SeedRequest > SeedRequestPtr;
typedef boost::shared_ptr< ::active_grasp::SeedRequest const> SeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::active_grasp::SeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::active_grasp::SeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::active_grasp::SeedRequest_<ContainerAllocator1> & lhs, const ::active_grasp::SeedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.seed == rhs.seed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::active_grasp::SeedRequest_<ContainerAllocator1> & lhs, const ::active_grasp::SeedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace active_grasp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::active_grasp::SeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::active_grasp::SeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::active_grasp::SeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::active_grasp::SeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::active_grasp::SeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::active_grasp::SeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::active_grasp::SeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56fd131f75eb969fd4909892624a2fdc";
  }

  static const char* value(const ::active_grasp::SeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56fd131f75eb969fULL;
  static const uint64_t static_value2 = 0xd4909892624a2fdcULL;
};

template<class ContainerAllocator>
struct DataType< ::active_grasp::SeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "active_grasp/SeedRequest";
  }

  static const char* value(const ::active_grasp::SeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::active_grasp::SeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 seed\n"
;
  }

  static const char* value(const ::active_grasp::SeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::active_grasp::SeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::active_grasp::SeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::active_grasp::SeedRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "seed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIVE_GRASP_MESSAGE_SEEDREQUEST_H
