// Generated by gencpp from file rosdemo_v3/ClearError.msg
// DO NOT EDIT!


#ifndef ROSDEMO_V3_MESSAGE_CLEARERROR_H
#define ROSDEMO_V3_MESSAGE_CLEARERROR_H

#include <ros/service_traits.h>


#include <rosdemo_v3/ClearErrorRequest.h>
#include <rosdemo_v3/ClearErrorResponse.h>


namespace rosdemo_v3
{

struct ClearError
{

typedef ClearErrorRequest Request;
typedef ClearErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearError
} // namespace rosdemo_v3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosdemo_v3::ClearError > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::rosdemo_v3::ClearError&) { return value(); }
};

template<>
struct DataType< ::rosdemo_v3::ClearError > {
  static const char* value()
  {
    return "rosdemo_v3/ClearError";
  }

  static const char* value(const ::rosdemo_v3::ClearError&) { return value(); }
};


// service_traits::MD5Sum< ::rosdemo_v3::ClearErrorRequest> should match
// service_traits::MD5Sum< ::rosdemo_v3::ClearError >
template<>
struct MD5Sum< ::rosdemo_v3::ClearErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosdemo_v3::ClearError >::value();
  }
  static const char* value(const ::rosdemo_v3::ClearErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdemo_v3::ClearErrorRequest> should match
// service_traits::DataType< ::rosdemo_v3::ClearError >
template<>
struct DataType< ::rosdemo_v3::ClearErrorRequest>
{
  static const char* value()
  {
    return DataType< ::rosdemo_v3::ClearError >::value();
  }
  static const char* value(const ::rosdemo_v3::ClearErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosdemo_v3::ClearErrorResponse> should match
// service_traits::MD5Sum< ::rosdemo_v3::ClearError >
template<>
struct MD5Sum< ::rosdemo_v3::ClearErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosdemo_v3::ClearError >::value();
  }
  static const char* value(const ::rosdemo_v3::ClearErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdemo_v3::ClearErrorResponse> should match
// service_traits::DataType< ::rosdemo_v3::ClearError >
template<>
struct DataType< ::rosdemo_v3::ClearErrorResponse>
{
  static const char* value()
  {
    return DataType< ::rosdemo_v3::ClearError >::value();
  }
  static const char* value(const ::rosdemo_v3::ClearErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSDEMO_V3_MESSAGE_CLEARERROR_H
