// Generated by gencpp from file rosdemo_v3/GetErrorIDRequest.msg
// DO NOT EDIT!


#ifndef ROSDEMO_V3_MESSAGE_GETERRORIDREQUEST_H
#define ROSDEMO_V3_MESSAGE_GETERRORIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosdemo_v3
{
template <class ContainerAllocator>
struct GetErrorIDRequest_
{
  typedef GetErrorIDRequest_<ContainerAllocator> Type;

  GetErrorIDRequest_()
    {
    }
  GetErrorIDRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetErrorIDRequest_

typedef ::rosdemo_v3::GetErrorIDRequest_<std::allocator<void> > GetErrorIDRequest;

typedef boost::shared_ptr< ::rosdemo_v3::GetErrorIDRequest > GetErrorIDRequestPtr;
typedef boost::shared_ptr< ::rosdemo_v3::GetErrorIDRequest const> GetErrorIDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rosdemo_v3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosdemo_v3/GetErrorIDRequest";
  }

  static const char* value(const ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetErrorIDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rosdemo_v3::GetErrorIDRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROSDEMO_V3_MESSAGE_GETERRORIDREQUEST_H
