// Generated by gencpp from file rosdemo_v3/Sync.msg
// DO NOT EDIT!


#ifndef ROSDEMO_V3_MESSAGE_SYNC_H
#define ROSDEMO_V3_MESSAGE_SYNC_H

#include <ros/service_traits.h>


#include <rosdemo_v3/SyncRequest.h>
#include <rosdemo_v3/SyncResponse.h>


namespace rosdemo_v3
{

struct Sync
{

typedef SyncRequest Request;
typedef SyncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sync
} // namespace rosdemo_v3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosdemo_v3::Sync > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::rosdemo_v3::Sync&) { return value(); }
};

template<>
struct DataType< ::rosdemo_v3::Sync > {
  static const char* value()
  {
    return "rosdemo_v3/Sync";
  }

  static const char* value(const ::rosdemo_v3::Sync&) { return value(); }
};


// service_traits::MD5Sum< ::rosdemo_v3::SyncRequest> should match
// service_traits::MD5Sum< ::rosdemo_v3::Sync >
template<>
struct MD5Sum< ::rosdemo_v3::SyncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosdemo_v3::Sync >::value();
  }
  static const char* value(const ::rosdemo_v3::SyncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdemo_v3::SyncRequest> should match
// service_traits::DataType< ::rosdemo_v3::Sync >
template<>
struct DataType< ::rosdemo_v3::SyncRequest>
{
  static const char* value()
  {
    return DataType< ::rosdemo_v3::Sync >::value();
  }
  static const char* value(const ::rosdemo_v3::SyncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosdemo_v3::SyncResponse> should match
// service_traits::MD5Sum< ::rosdemo_v3::Sync >
template<>
struct MD5Sum< ::rosdemo_v3::SyncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosdemo_v3::Sync >::value();
  }
  static const char* value(const ::rosdemo_v3::SyncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdemo_v3::SyncResponse> should match
// service_traits::DataType< ::rosdemo_v3::Sync >
template<>
struct DataType< ::rosdemo_v3::SyncResponse>
{
  static const char* value()
  {
    return DataType< ::rosdemo_v3::Sync >::value();
  }
  static const char* value(const ::rosdemo_v3::SyncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSDEMO_V3_MESSAGE_SYNC_H
