// Generated by gencpp from file dobot_v4_bringup/AccL.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_ACCL_H
#define DOBOT_V4_BRINGUP_MESSAGE_ACCL_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/AccLRequest.h>
#include <dobot_v4_bringup/AccLResponse.h>


namespace dobot_v4_bringup
{

struct AccL
{

typedef AccLRequest Request;
typedef AccLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AccL
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::AccL > {
  static const char* value()
  {
    return "941d9ecd0f5402311261de883bef5059";
  }

  static const char* value(const ::dobot_v4_bringup::AccL&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::AccL > {
  static const char* value()
  {
    return "dobot_v4_bringup/AccL";
  }

  static const char* value(const ::dobot_v4_bringup::AccL&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::AccLRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::AccL >
template<>
struct MD5Sum< ::dobot_v4_bringup::AccLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::AccL >::value();
  }
  static const char* value(const ::dobot_v4_bringup::AccLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::AccLRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::AccL >
template<>
struct DataType< ::dobot_v4_bringup::AccLRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::AccL >::value();
  }
  static const char* value(const ::dobot_v4_bringup::AccLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::AccLResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::AccL >
template<>
struct MD5Sum< ::dobot_v4_bringup::AccLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::AccL >::value();
  }
  static const char* value(const ::dobot_v4_bringup::AccLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::AccLResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::AccL >
template<>
struct DataType< ::dobot_v4_bringup::AccLResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::AccL >::value();
  }
  static const char* value(const ::dobot_v4_bringup::AccLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_ACCL_H
