// Generated by gencpp from file dobot_v4_bringup/CalcUser.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_CALCUSER_H
#define DOBOT_V4_BRINGUP_MESSAGE_CALCUSER_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/CalcUserRequest.h>
#include <dobot_v4_bringup/CalcUserResponse.h>


namespace dobot_v4_bringup
{

struct CalcUser
{

typedef CalcUserRequest Request;
typedef CalcUserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalcUser
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::CalcUser > {
  static const char* value()
  {
    return "2ca5e99fbfe69882ece191e51f4e52e0";
  }

  static const char* value(const ::dobot_v4_bringup::CalcUser&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::CalcUser > {
  static const char* value()
  {
    return "dobot_v4_bringup/CalcUser";
  }

  static const char* value(const ::dobot_v4_bringup::CalcUser&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::CalcUserRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::CalcUser >
template<>
struct MD5Sum< ::dobot_v4_bringup::CalcUserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::CalcUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CalcUserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::CalcUserRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::CalcUser >
template<>
struct DataType< ::dobot_v4_bringup::CalcUserRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::CalcUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CalcUserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::CalcUserResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::CalcUser >
template<>
struct MD5Sum< ::dobot_v4_bringup::CalcUserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::CalcUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CalcUserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::CalcUserResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::CalcUser >
template<>
struct DataType< ::dobot_v4_bringup::CalcUserResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::CalcUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CalcUserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_CALCUSER_H
