// Generated by gencpp from file dobot_v4_bringup/Circle.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_CIRCLE_H
#define DOBOT_V4_BRINGUP_MESSAGE_CIRCLE_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/CircleRequest.h>
#include <dobot_v4_bringup/CircleResponse.h>


namespace dobot_v4_bringup
{

struct Circle
{

typedef CircleRequest Request;
typedef CircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Circle
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::Circle > {
  static const char* value()
  {
    return "ea8941f1924ced8f040f9ac672c828e7";
  }

  static const char* value(const ::dobot_v4_bringup::Circle&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::Circle > {
  static const char* value()
  {
    return "dobot_v4_bringup/Circle";
  }

  static const char* value(const ::dobot_v4_bringup::Circle&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::CircleRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::Circle >
template<>
struct MD5Sum< ::dobot_v4_bringup::CircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::Circle >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::CircleRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::Circle >
template<>
struct DataType< ::dobot_v4_bringup::CircleRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::Circle >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::CircleResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::Circle >
template<>
struct MD5Sum< ::dobot_v4_bringup::CircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::Circle >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::CircleResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::Circle >
template<>
struct DataType< ::dobot_v4_bringup::CircleResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::Circle >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_CIRCLE_H
