// Generated by gencpp from file dobot_v4_bringup/CP.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_CP_H
#define DOBOT_V4_BRINGUP_MESSAGE_CP_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/CPRequest.h>
#include <dobot_v4_bringup/CPResponse.h>


namespace dobot_v4_bringup
{

struct CP
{

typedef CPRequest Request;
typedef CPResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CP
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::CP > {
  static const char* value()
  {
    return "941d9ecd0f5402311261de883bef5059";
  }

  static const char* value(const ::dobot_v4_bringup::CP&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::CP > {
  static const char* value()
  {
    return "dobot_v4_bringup/CP";
  }

  static const char* value(const ::dobot_v4_bringup::CP&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::CPRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::CP >
template<>
struct MD5Sum< ::dobot_v4_bringup::CPRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::CP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CPRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::CPRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::CP >
template<>
struct DataType< ::dobot_v4_bringup::CPRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::CP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CPRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::CPResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::CP >
template<>
struct MD5Sum< ::dobot_v4_bringup::CPResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::CP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CPResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::CPResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::CP >
template<>
struct DataType< ::dobot_v4_bringup::CPResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::CP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::CPResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_CP_H
