// Generated by gencpp from file dobot_v4_bringup/EmergencyStop.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_EMERGENCYSTOP_H
#define DOBOT_V4_BRINGUP_MESSAGE_EMERGENCYSTOP_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/EmergencyStopRequest.h>
#include <dobot_v4_bringup/EmergencyStopResponse.h>


namespace dobot_v4_bringup
{

struct EmergencyStop
{

typedef EmergencyStopRequest Request;
typedef EmergencyStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmergencyStop
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::EmergencyStop > {
  static const char* value()
  {
    return "e2f95961203d3c57387d7d792b34055f";
  }

  static const char* value(const ::dobot_v4_bringup::EmergencyStop&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::EmergencyStop > {
  static const char* value()
  {
    return "dobot_v4_bringup/EmergencyStop";
  }

  static const char* value(const ::dobot_v4_bringup::EmergencyStop&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::EmergencyStopRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::EmergencyStop >
template<>
struct MD5Sum< ::dobot_v4_bringup::EmergencyStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::EmergencyStop >::value();
  }
  static const char* value(const ::dobot_v4_bringup::EmergencyStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::EmergencyStopRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::EmergencyStop >
template<>
struct DataType< ::dobot_v4_bringup::EmergencyStopRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::EmergencyStop >::value();
  }
  static const char* value(const ::dobot_v4_bringup::EmergencyStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::EmergencyStopResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::EmergencyStop >
template<>
struct MD5Sum< ::dobot_v4_bringup::EmergencyStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::EmergencyStop >::value();
  }
  static const char* value(const ::dobot_v4_bringup::EmergencyStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::EmergencyStopResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::EmergencyStop >
template<>
struct DataType< ::dobot_v4_bringup::EmergencyStopResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::EmergencyStop >::value();
  }
  static const char* value(const ::dobot_v4_bringup::EmergencyStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_EMERGENCYSTOP_H
