// Generated by gencpp from file dobot_v4_bringup/GetCurrentCommandId.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_GETCURRENTCOMMANDID_H
#define DOBOT_V4_BRINGUP_MESSAGE_GETCURRENTCOMMANDID_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/GetCurrentCommandIdRequest.h>
#include <dobot_v4_bringup/GetCurrentCommandIdResponse.h>


namespace dobot_v4_bringup
{

struct GetCurrentCommandId
{

typedef GetCurrentCommandIdRequest Request;
typedef GetCurrentCommandIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentCommandId
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::GetCurrentCommandId > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::dobot_v4_bringup::GetCurrentCommandId&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::GetCurrentCommandId > {
  static const char* value()
  {
    return "dobot_v4_bringup/GetCurrentCommandId";
  }

  static const char* value(const ::dobot_v4_bringup::GetCurrentCommandId&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::GetCurrentCommandIdRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::GetCurrentCommandId >
template<>
struct MD5Sum< ::dobot_v4_bringup::GetCurrentCommandIdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::GetCurrentCommandId >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetCurrentCommandIdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::GetCurrentCommandIdRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::GetCurrentCommandId >
template<>
struct DataType< ::dobot_v4_bringup::GetCurrentCommandIdRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::GetCurrentCommandId >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetCurrentCommandIdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::GetCurrentCommandIdResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::GetCurrentCommandId >
template<>
struct MD5Sum< ::dobot_v4_bringup::GetCurrentCommandIdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::GetCurrentCommandId >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetCurrentCommandIdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::GetCurrentCommandIdResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::GetCurrentCommandId >
template<>
struct DataType< ::dobot_v4_bringup::GetCurrentCommandIdResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::GetCurrentCommandId >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetCurrentCommandIdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_GETCURRENTCOMMANDID_H
