// Generated by gencpp from file dobot_v4_bringup/GetInputFloat.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_GETINPUTFLOAT_H
#define DOBOT_V4_BRINGUP_MESSAGE_GETINPUTFLOAT_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/GetInputFloatRequest.h>
#include <dobot_v4_bringup/GetInputFloatResponse.h>


namespace dobot_v4_bringup
{

struct GetInputFloat
{

typedef GetInputFloatRequest Request;
typedef GetInputFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInputFloat
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::GetInputFloat > {
  static const char* value()
  {
    return "4f4e99215b78104599bc3fd88b4cdc1c";
  }

  static const char* value(const ::dobot_v4_bringup::GetInputFloat&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::GetInputFloat > {
  static const char* value()
  {
    return "dobot_v4_bringup/GetInputFloat";
  }

  static const char* value(const ::dobot_v4_bringup::GetInputFloat&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::GetInputFloatRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::GetInputFloat >
template<>
struct MD5Sum< ::dobot_v4_bringup::GetInputFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::GetInputFloat >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetInputFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::GetInputFloatRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::GetInputFloat >
template<>
struct DataType< ::dobot_v4_bringup::GetInputFloatRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::GetInputFloat >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetInputFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::GetInputFloatResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::GetInputFloat >
template<>
struct MD5Sum< ::dobot_v4_bringup::GetInputFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::GetInputFloat >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetInputFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::GetInputFloatResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::GetInputFloat >
template<>
struct DataType< ::dobot_v4_bringup::GetInputFloatResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::GetInputFloat >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetInputFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_GETINPUTFLOAT_H
