// Generated by gencpp from file dobot_v4_bringup/GetPoseRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_GETPOSEREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_GETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct GetPoseRequest_
{
  typedef GetPoseRequest_<ContainerAllocator> Type;

  GetPoseRequest_()
    : user()
    , tool()  {
    }
  GetPoseRequest_(const ContainerAllocator& _alloc)
    : user(_alloc)
    , tool(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_type;
  _user_type user;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tool_type;
  _tool_type tool;





  typedef boost::shared_ptr< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseRequest_

typedef ::dobot_v4_bringup::GetPoseRequest_<std::allocator<void> > GetPoseRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::GetPoseRequest > GetPoseRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::GetPoseRequest const> GetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user == rhs.user &&
    lhs.tool == rhs.tool;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788c772522634408eff9c0a2cd484e08";
  }

  static const char* value(const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788c772522634408ULL;
  static const uint64_t static_value2 = 0xeff9c0a2cd484e08ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/GetPoseRequest";
  }

  static const char* value(const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n"
"string tool\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
      stream.next(m.tool);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::GetPoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tool: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tool);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_GETPOSEREQUEST_H
