// Generated by gencpp from file dobot_v4_bringup/GetPose.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_GETPOSE_H
#define DOBOT_V4_BRINGUP_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/GetPoseRequest.h>
#include <dobot_v4_bringup/GetPoseResponse.h>


namespace dobot_v4_bringup
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::GetPose > {
  static const char* value()
  {
    return "6e2821e46ee2b08788c23c3b4447f439";
  }

  static const char* value(const ::dobot_v4_bringup::GetPose&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::GetPose > {
  static const char* value()
  {
    return "dobot_v4_bringup/GetPose";
  }

  static const char* value(const ::dobot_v4_bringup::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::GetPoseRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::GetPose >
template<>
struct MD5Sum< ::dobot_v4_bringup::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::GetPose >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::GetPoseRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::GetPose >
template<>
struct DataType< ::dobot_v4_bringup::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::GetPose >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::GetPoseResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::GetPose >
template<>
struct MD5Sum< ::dobot_v4_bringup::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::GetPose >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::GetPoseResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::GetPose >
template<>
struct DataType< ::dobot_v4_bringup::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::GetPose >::value();
  }
  static const char* value(const ::dobot_v4_bringup::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_GETPOSE_H
