// Generated by gencpp from file dobot_v4_bringup/MovLIO.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_MOVLIO_H
#define DOBOT_V4_BRINGUP_MESSAGE_MOVLIO_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/MovLIORequest.h>
#include <dobot_v4_bringup/MovLIOResponse.h>


namespace dobot_v4_bringup
{

struct MovLIO
{

typedef MovLIORequest Request;
typedef MovLIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovLIO
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::MovLIO > {
  static const char* value()
  {
    return "b1cf53f9f44e517c793a913e7740569a";
  }

  static const char* value(const ::dobot_v4_bringup::MovLIO&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::MovLIO > {
  static const char* value()
  {
    return "dobot_v4_bringup/MovLIO";
  }

  static const char* value(const ::dobot_v4_bringup::MovLIO&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::MovLIORequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::MovLIO >
template<>
struct MD5Sum< ::dobot_v4_bringup::MovLIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::MovLIO >::value();
  }
  static const char* value(const ::dobot_v4_bringup::MovLIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::MovLIORequest> should match
// service_traits::DataType< ::dobot_v4_bringup::MovLIO >
template<>
struct DataType< ::dobot_v4_bringup::MovLIORequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::MovLIO >::value();
  }
  static const char* value(const ::dobot_v4_bringup::MovLIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::MovLIOResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::MovLIO >
template<>
struct MD5Sum< ::dobot_v4_bringup::MovLIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::MovLIO >::value();
  }
  static const char* value(const ::dobot_v4_bringup::MovLIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::MovLIOResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::MovLIO >
template<>
struct DataType< ::dobot_v4_bringup::MovLIOResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::MovLIO >::value();
  }
  static const char* value(const ::dobot_v4_bringup::MovLIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_MOVLIO_H
