// Generated by gencpp from file dobot_v4_bringup/RelMovLTool.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_RELMOVLTOOL_H
#define DOBOT_V4_BRINGUP_MESSAGE_RELMOVLTOOL_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/RelMovLToolRequest.h>
#include <dobot_v4_bringup/RelMovLToolResponse.h>


namespace dobot_v4_bringup
{

struct RelMovLTool
{

typedef RelMovLToolRequest Request;
typedef RelMovLToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelMovLTool
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::RelMovLTool > {
  static const char* value()
  {
    return "acbcde02d4dabec81bbbb65ee94d60dc";
  }

  static const char* value(const ::dobot_v4_bringup::RelMovLTool&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::RelMovLTool > {
  static const char* value()
  {
    return "dobot_v4_bringup/RelMovLTool";
  }

  static const char* value(const ::dobot_v4_bringup::RelMovLTool&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::RelMovLToolRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::RelMovLTool >
template<>
struct MD5Sum< ::dobot_v4_bringup::RelMovLToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RelMovLToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::RelMovLToolRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::RelMovLTool >
template<>
struct DataType< ::dobot_v4_bringup::RelMovLToolRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RelMovLToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::RelMovLToolResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::RelMovLTool >
template<>
struct MD5Sum< ::dobot_v4_bringup::RelMovLToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RelMovLToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::RelMovLToolResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::RelMovLTool >
template<>
struct DataType< ::dobot_v4_bringup::RelMovLToolResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RelMovLToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_RELMOVLTOOL_H
