// Generated by gencpp from file dobot_v4_bringup/RelMovJToolRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_RELMOVJTOOLREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_RELMOVJTOOLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct RelMovJToolRequest_
{
  typedef RelMovJToolRequest_<ContainerAllocator> Type;

  RelMovJToolRequest_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)
    , paramValue()  {
    }
  RelMovJToolRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;

   typedef double _e_type;
  _e_type e;

   typedef double _f_type;
  _f_type f;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelMovJToolRequest_

typedef ::dobot_v4_bringup::RelMovJToolRequest_<std::allocator<void> > RelMovJToolRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::RelMovJToolRequest > RelMovJToolRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::RelMovJToolRequest const> RelMovJToolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e &&
    lhs.f == rhs.f &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eabb4f33eb0af81449dab9472a3a789";
  }

  static const char* value(const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eabb4f33eb0af81ULL;
  static const uint64_t static_value2 = 0x449dab9472a3a789ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/RelMovJToolRequest";
  }

  static const char* value(const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n"
"float64 b\n"
"float64 c\n"
"float64 d\n"
"float64 e\n"
"float64 f\n"
"string[] paramValue\n"
"\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
      stream.next(m.f);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelMovJToolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::RelMovJToolRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "e: ";
    Printer<double>::stream(s, indent + "  ", v.e);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "f: ";
    Printer<double>::stream(s, indent + "  ", v.f);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "paramValue: ";
    if (v.paramValue.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.paramValue[i]);
    }
    if (v.paramValue.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_RELMOVJTOOLREQUEST_H
