// Generated by gencpp from file dobot_v4_bringup/RunScript.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_RUNSCRIPT_H
#define DOBOT_V4_BRINGUP_MESSAGE_RUNSCRIPT_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/RunScriptRequest.h>
#include <dobot_v4_bringup/RunScriptResponse.h>


namespace dobot_v4_bringup
{

struct RunScript
{

typedef RunScriptRequest Request;
typedef RunScriptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunScript
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::RunScript > {
  static const char* value()
  {
    return "7a897c62a8cb97cf0bd8a288103abd8a";
  }

  static const char* value(const ::dobot_v4_bringup::RunScript&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::RunScript > {
  static const char* value()
  {
    return "dobot_v4_bringup/RunScript";
  }

  static const char* value(const ::dobot_v4_bringup::RunScript&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::RunScriptRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::RunScript >
template<>
struct MD5Sum< ::dobot_v4_bringup::RunScriptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::RunScript >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RunScriptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::RunScriptRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::RunScript >
template<>
struct DataType< ::dobot_v4_bringup::RunScriptRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::RunScript >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RunScriptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::RunScriptResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::RunScript >
template<>
struct MD5Sum< ::dobot_v4_bringup::RunScriptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::RunScript >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RunScriptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::RunScriptResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::RunScript >
template<>
struct DataType< ::dobot_v4_bringup::RunScriptResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::RunScript >::value();
  }
  static const char* value(const ::dobot_v4_bringup::RunScriptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_RUNSCRIPT_H
