// Generated by gencpp from file dobot_v4_bringup/ServoP.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SERVOP_H
#define DOBOT_V4_BRINGUP_MESSAGE_SERVOP_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/ServoPRequest.h>
#include <dobot_v4_bringup/ServoPResponse.h>


namespace dobot_v4_bringup
{

struct ServoP
{

typedef ServoPRequest Request;
typedef ServoPResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoP
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::ServoP > {
  static const char* value()
  {
    return "acbcde02d4dabec81bbbb65ee94d60dc";
  }

  static const char* value(const ::dobot_v4_bringup::ServoP&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::ServoP > {
  static const char* value()
  {
    return "dobot_v4_bringup/ServoP";
  }

  static const char* value(const ::dobot_v4_bringup::ServoP&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::ServoPRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::ServoP >
template<>
struct MD5Sum< ::dobot_v4_bringup::ServoPRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::ServoP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ServoPRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::ServoPRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::ServoP >
template<>
struct DataType< ::dobot_v4_bringup::ServoPRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::ServoP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ServoPRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::ServoPResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::ServoP >
template<>
struct MD5Sum< ::dobot_v4_bringup::ServoPResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::ServoP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ServoPResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::ServoPResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::ServoP >
template<>
struct DataType< ::dobot_v4_bringup::ServoPResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::ServoP >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ServoPResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SERVOP_H
