// Generated by gencpp from file dobot_v4_bringup/SetBackDistance.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETBACKDISTANCE_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETBACKDISTANCE_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/SetBackDistanceRequest.h>
#include <dobot_v4_bringup/SetBackDistanceResponse.h>


namespace dobot_v4_bringup
{

struct SetBackDistance
{

typedef SetBackDistanceRequest Request;
typedef SetBackDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBackDistance
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::SetBackDistance > {
  static const char* value()
  {
    return "b5aedf238494aa6f191a1d1512d4f21b";
  }

  static const char* value(const ::dobot_v4_bringup::SetBackDistance&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::SetBackDistance > {
  static const char* value()
  {
    return "dobot_v4_bringup/SetBackDistance";
  }

  static const char* value(const ::dobot_v4_bringup::SetBackDistance&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::SetBackDistanceRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetBackDistance >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetBackDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetBackDistance >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetBackDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetBackDistanceRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::SetBackDistance >
template<>
struct DataType< ::dobot_v4_bringup::SetBackDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetBackDistance >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetBackDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::SetBackDistanceResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetBackDistance >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetBackDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetBackDistance >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetBackDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetBackDistanceResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::SetBackDistance >
template<>
struct DataType< ::dobot_v4_bringup::SetBackDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetBackDistance >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetBackDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETBACKDISTANCE_H
