// Generated by gencpp from file dobot_v4_bringup/SetCoils.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETCOILS_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETCOILS_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/SetCoilsRequest.h>
#include <dobot_v4_bringup/SetCoilsResponse.h>


namespace dobot_v4_bringup
{

struct SetCoils
{

typedef SetCoilsRequest Request;
typedef SetCoilsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCoils
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::SetCoils > {
  static const char* value()
  {
    return "b96ff1589f34f54f6a9a01053552fb29";
  }

  static const char* value(const ::dobot_v4_bringup::SetCoils&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::SetCoils > {
  static const char* value()
  {
    return "dobot_v4_bringup/SetCoils";
  }

  static const char* value(const ::dobot_v4_bringup::SetCoils&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::SetCoilsRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetCoils >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetCoilsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetCoils >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetCoilsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetCoilsRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::SetCoils >
template<>
struct DataType< ::dobot_v4_bringup::SetCoilsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetCoils >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetCoilsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::SetCoilsResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetCoils >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetCoilsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetCoils >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetCoilsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetCoilsResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::SetCoils >
template<>
struct DataType< ::dobot_v4_bringup::SetCoilsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetCoils >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetCoilsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETCOILS_H
