// Generated by gencpp from file dobot_v4_bringup/SetOutputBoolRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETOUTPUTBOOLREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETOUTPUTBOOLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct SetOutputBoolRequest_
{
  typedef SetOutputBoolRequest_<ContainerAllocator> Type;

  SetOutputBoolRequest_()
    : address(0)
    , value(0)  {
    }
  SetOutputBoolRequest_(const ContainerAllocator& _alloc)
    : address(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int32_t _address_type;
  _address_type address;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOutputBoolRequest_

typedef ::dobot_v4_bringup::SetOutputBoolRequest_<std::allocator<void> > SetOutputBoolRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputBoolRequest > SetOutputBoolRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputBoolRequest const> SetOutputBoolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d1f76242de856e3a44fa6454dab1b8";
  }

  static const char* value(const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d1f76242de856eULL;
  static const uint64_t static_value2 = 0x3a44fa6454dab1b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/SetOutputBoolRequest";
  }

  static const char* value(const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 address\n"
"int32 value\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOutputBoolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::SetOutputBoolRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETOUTPUTBOOLREQUEST_H
