// Generated by gencpp from file dobot_v4_bringup/SetOutputFloatRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETOUTPUTFLOATREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETOUTPUTFLOATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct SetOutputFloatRequest_
{
  typedef SetOutputFloatRequest_<ContainerAllocator> Type;

  SetOutputFloatRequest_()
    : address(0)
    , value(0.0)  {
    }
  SetOutputFloatRequest_(const ContainerAllocator& _alloc)
    : address(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _address_type;
  _address_type address;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOutputFloatRequest_

typedef ::dobot_v4_bringup::SetOutputFloatRequest_<std::allocator<void> > SetOutputFloatRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputFloatRequest > SetOutputFloatRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::SetOutputFloatRequest const> SetOutputFloatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65cc2d21cc86194218dba08d123688f9";
  }

  static const char* value(const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65cc2d21cc861942ULL;
  static const uint64_t static_value2 = 0x18dba08d123688f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/SetOutputFloatRequest";
  }

  static const char* value(const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 address\n"
"float64 value\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOutputFloatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::SetOutputFloatRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETOUTPUTFLOATREQUEST_H
