// Generated by gencpp from file dobot_v4_bringup/SetSafeSkinRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETSAFESKINREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETSAFESKINREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct SetSafeSkinRequest_
{
  typedef SetSafeSkinRequest_<ContainerAllocator> Type;

  SetSafeSkinRequest_()
    : part(0)
    , status(0)  {
    }
  SetSafeSkinRequest_(const ContainerAllocator& _alloc)
    : part(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef int32_t _part_type;
  _part_type part;

   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSafeSkinRequest_

typedef ::dobot_v4_bringup::SetSafeSkinRequest_<std::allocator<void> > SetSafeSkinRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::SetSafeSkinRequest > SetSafeSkinRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::SetSafeSkinRequest const> SetSafeSkinRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator2> & rhs)
{
  return lhs.part == rhs.part &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e239564c4c5f69979a5049ca9ed6abf1";
  }

  static const char* value(const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe239564c4c5f6997ULL;
  static const uint64_t static_value2 = 0x9a5049ca9ed6abf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/SetSafeSkinRequest";
  }

  static const char* value(const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 part\n"
"int32 status\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.part);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSafeSkinRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::SetSafeSkinRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "part: ";
    Printer<int32_t>::stream(s, indent + "  ", v.part);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETSAFESKINREQUEST_H
