// Generated by gencpp from file dobot_v4_bringup/SetSafeWallEnable.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETSAFEWALLENABLE_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETSAFEWALLENABLE_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/SetSafeWallEnableRequest.h>
#include <dobot_v4_bringup/SetSafeWallEnableResponse.h>


namespace dobot_v4_bringup
{

struct SetSafeWallEnable
{

typedef SetSafeWallEnableRequest Request;
typedef SetSafeWallEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSafeWallEnable
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::SetSafeWallEnable > {
  static const char* value()
  {
    return "c9ffa71f693aabb4ec23d98e0cce7e29";
  }

  static const char* value(const ::dobot_v4_bringup::SetSafeWallEnable&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::SetSafeWallEnable > {
  static const char* value()
  {
    return "dobot_v4_bringup/SetSafeWallEnable";
  }

  static const char* value(const ::dobot_v4_bringup::SetSafeWallEnable&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::SetSafeWallEnableRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetSafeWallEnable >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetSafeWallEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetSafeWallEnable >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetSafeWallEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetSafeWallEnableRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::SetSafeWallEnable >
template<>
struct DataType< ::dobot_v4_bringup::SetSafeWallEnableRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetSafeWallEnable >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetSafeWallEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::SetSafeWallEnableResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetSafeWallEnable >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetSafeWallEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetSafeWallEnable >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetSafeWallEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetSafeWallEnableResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::SetSafeWallEnable >
template<>
struct DataType< ::dobot_v4_bringup::SetSafeWallEnableResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetSafeWallEnable >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetSafeWallEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETSAFEWALLENABLE_H
