// Generated by gencpp from file dobot_v4_bringup/SetToolModeRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETTOOLMODEREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETTOOLMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct SetToolModeRequest_
{
  typedef SetToolModeRequest_<ContainerAllocator> Type;

  SetToolModeRequest_()
    : mode(0)
    , type(0)  {
    }
  SetToolModeRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetToolModeRequest_

typedef ::dobot_v4_bringup::SetToolModeRequest_<std::allocator<void> > SetToolModeRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::SetToolModeRequest > SetToolModeRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::SetToolModeRequest const> SetToolModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eebc226c7b2033ee8885e6fed0e5c18";
  }

  static const char* value(const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eebc226c7b2033eULL;
  static const uint64_t static_value2 = 0xe8885e6fed0e5c18ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/SetToolModeRequest";
  }

  static const char* value(const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
"int32 type\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetToolModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::SetToolModeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETTOOLMODEREQUEST_H
