// Generated by gencpp from file dobot_v4_bringup/SetUser.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SETUSER_H
#define DOBOT_V4_BRINGUP_MESSAGE_SETUSER_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/SetUserRequest.h>
#include <dobot_v4_bringup/SetUserResponse.h>


namespace dobot_v4_bringup
{

struct SetUser
{

typedef SetUserRequest Request;
typedef SetUserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUser
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::SetUser > {
  static const char* value()
  {
    return "eb22f0d11f25c9fa141244b7089d06e0";
  }

  static const char* value(const ::dobot_v4_bringup::SetUser&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::SetUser > {
  static const char* value()
  {
    return "dobot_v4_bringup/SetUser";
  }

  static const char* value(const ::dobot_v4_bringup::SetUser&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::SetUserRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetUser >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetUserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetUserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetUserRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::SetUser >
template<>
struct DataType< ::dobot_v4_bringup::SetUserRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetUserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::SetUserResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::SetUser >
template<>
struct MD5Sum< ::dobot_v4_bringup::SetUserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::SetUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetUserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::SetUserResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::SetUser >
template<>
struct DataType< ::dobot_v4_bringup::SetUserResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::SetUser >::value();
  }
  static const char* value(const ::dobot_v4_bringup::SetUserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SETUSER_H
