// Generated by gencpp from file dobot_v4_bringup/SpeedFactorRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_SPEEDFACTORREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_SPEEDFACTORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct SpeedFactorRequest_
{
  typedef SpeedFactorRequest_<ContainerAllocator> Type;

  SpeedFactorRequest_()
    : ratio(0)  {
    }
  SpeedFactorRequest_(const ContainerAllocator& _alloc)
    : ratio(0)  {
  (void)_alloc;
    }



   typedef int32_t _ratio_type;
  _ratio_type ratio;





  typedef boost::shared_ptr< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpeedFactorRequest_

typedef ::dobot_v4_bringup::SpeedFactorRequest_<std::allocator<void> > SpeedFactorRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::SpeedFactorRequest > SpeedFactorRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::SpeedFactorRequest const> SpeedFactorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ratio == rhs.ratio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "132c75cf99b8d9ca8c3bb6253da8b912";
  }

  static const char* value(const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x132c75cf99b8d9caULL;
  static const uint64_t static_value2 = 0x8c3bb6253da8b912ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/SpeedFactorRequest";
  }

  static const char* value(const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ratio\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ratio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeedFactorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::SpeedFactorRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ratio: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ratio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_SPEEDFACTORREQUEST_H
