// Generated by gencpp from file dobot_v4_bringup/StartPathRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_STARTPATHREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_STARTPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct StartPathRequest_
{
  typedef StartPathRequest_<ContainerAllocator> Type;

  StartPathRequest_()
    : traceName()
    , paramValue()  {
    }
  StartPathRequest_(const ContainerAllocator& _alloc)
    : traceName(_alloc)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _traceName_type;
  _traceName_type traceName;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartPathRequest_

typedef ::dobot_v4_bringup::StartPathRequest_<std::allocator<void> > StartPathRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::StartPathRequest > StartPathRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::StartPathRequest const> StartPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.traceName == rhs.traceName &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992919c8b1925d3c449cc29133c76354";
  }

  static const char* value(const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992919c8b1925d3cULL;
  static const uint64_t static_value2 = 0x449cc29133c76354ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/StartPathRequest";
  }

  static const char* value(const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string traceName\n"
"string[] paramValue\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traceName);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::StartPathRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "traceName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.traceName);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "paramValue: ";
    if (v.paramValue.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.paramValue[i]);
    }
    if (v.paramValue.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_STARTPATHREQUEST_H
