// Generated by gencpp from file dobot_v4_bringup/ToolDI.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_TOOLDI_H
#define DOBOT_V4_BRINGUP_MESSAGE_TOOLDI_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/ToolDIRequest.h>
#include <dobot_v4_bringup/ToolDIResponse.h>


namespace dobot_v4_bringup
{

struct ToolDI
{

typedef ToolDIRequest Request;
typedef ToolDIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToolDI
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::ToolDI > {
  static const char* value()
  {
    return "6d753c0adbdd6c06a6eb5c36aec96b0c";
  }

  static const char* value(const ::dobot_v4_bringup::ToolDI&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::ToolDI > {
  static const char* value()
  {
    return "dobot_v4_bringup/ToolDI";
  }

  static const char* value(const ::dobot_v4_bringup::ToolDI&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::ToolDIRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::ToolDI >
template<>
struct MD5Sum< ::dobot_v4_bringup::ToolDIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::ToolDI >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ToolDIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::ToolDIRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::ToolDI >
template<>
struct DataType< ::dobot_v4_bringup::ToolDIRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::ToolDI >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ToolDIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::ToolDIResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::ToolDI >
template<>
struct MD5Sum< ::dobot_v4_bringup::ToolDIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::ToolDI >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ToolDIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::ToolDIResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::ToolDI >
template<>
struct DataType< ::dobot_v4_bringup::ToolDIResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::ToolDI >::value();
  }
  static const char* value(const ::dobot_v4_bringup::ToolDIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_TOOLDI_H
