// Generated by gencpp from file dobot_v4_bringup/VelJ.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_VELJ_H
#define DOBOT_V4_BRINGUP_MESSAGE_VELJ_H

#include <ros/service_traits.h>


#include <dobot_v4_bringup/VelJRequest.h>
#include <dobot_v4_bringup/VelJResponse.h>


namespace dobot_v4_bringup
{

struct VelJ
{

typedef VelJRequest Request;
typedef VelJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelJ
} // namespace dobot_v4_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_v4_bringup::VelJ > {
  static const char* value()
  {
    return "941d9ecd0f5402311261de883bef5059";
  }

  static const char* value(const ::dobot_v4_bringup::VelJ&) { return value(); }
};

template<>
struct DataType< ::dobot_v4_bringup::VelJ > {
  static const char* value()
  {
    return "dobot_v4_bringup/VelJ";
  }

  static const char* value(const ::dobot_v4_bringup::VelJ&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_v4_bringup::VelJRequest> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::VelJ >
template<>
struct MD5Sum< ::dobot_v4_bringup::VelJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::VelJ >::value();
  }
  static const char* value(const ::dobot_v4_bringup::VelJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::VelJRequest> should match
// service_traits::DataType< ::dobot_v4_bringup::VelJ >
template<>
struct DataType< ::dobot_v4_bringup::VelJRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::VelJ >::value();
  }
  static const char* value(const ::dobot_v4_bringup::VelJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_v4_bringup::VelJResponse> should match
// service_traits::MD5Sum< ::dobot_v4_bringup::VelJ >
template<>
struct MD5Sum< ::dobot_v4_bringup::VelJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_v4_bringup::VelJ >::value();
  }
  static const char* value(const ::dobot_v4_bringup::VelJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_v4_bringup::VelJResponse> should match
// service_traits::DataType< ::dobot_v4_bringup::VelJ >
template<>
struct DataType< ::dobot_v4_bringup::VelJResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_v4_bringup::VelJ >::value();
  }
  static const char* value(const ::dobot_v4_bringup::VelJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_VELJ_H
