// Generated by gencpp from file dobot_v4_bringup/VelJRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_V4_BRINGUP_MESSAGE_VELJREQUEST_H
#define DOBOT_V4_BRINGUP_MESSAGE_VELJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_v4_bringup
{
template <class ContainerAllocator>
struct VelJRequest_
{
  typedef VelJRequest_<ContainerAllocator> Type;

  VelJRequest_()
    : r(0)  {
    }
  VelJRequest_(const ContainerAllocator& _alloc)
    : r(0)  {
  (void)_alloc;
    }



   typedef int32_t _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelJRequest_

typedef ::dobot_v4_bringup::VelJRequest_<std::allocator<void> > VelJRequest;

typedef boost::shared_ptr< ::dobot_v4_bringup::VelJRequest > VelJRequestPtr;
typedef boost::shared_ptr< ::dobot_v4_bringup::VelJRequest const> VelJRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator1> & lhs, const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_v4_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa7eba76ae20db2204a8f1d4b9816c23";
  }

  static const char* value(const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa7eba76ae20db22ULL;
  static const uint64_t static_value2 = 0x04a8f1d4b9816c23ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_v4_bringup/VelJRequest";
  }

  static const char* value(const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 r\n"
;
  }

  static const char* value(const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelJRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_v4_bringup::VelJRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_v4_bringup::VelJRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "r: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_V4_BRINGUP_MESSAGE_VELJREQUEST_H
